language: php

sudo: false

cache:
  directories:
  - vendor

php:
  - 7.0
  - 7.1
  - 7.2

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit
  - vendor/bin/phpstan analyse -l 6 src

branches:
  only:
    - master
